### ISSUE TITLE
ELR 1.12.2

### ISSUE THREAD

**Issue by Fox1kFeed** [lomik31/ELR#1]
Привет. Хочу купить у тебя ресурспак ELR  для 1.12.2
По стоимости договоримся, надеюсь цену заламывать не будешь.
На ютубе я тебе писал.

**Comment by lomik31** [comment]
Ну смотри. Дело в том, что с версии 1.12 прошло много времени и многое изменилось. В частности структура самих файлов, модели сущностей самих блоков (таких, как сундук, например). Поэтому качественная работа над этим может занять много времени. Поэтому могу предложить сделать не полный порт текущей версии. У меня есть некоторые наработки на эту версию, поэтому если совместить их и рп на новую версию может выйти в целом неплохо, но нужно понимать, что он (рп) не совсем такой же. Где-то иные текстуры, где-то отсутствие моделей. В целом, скорее всего, не существенно, но тем не менее. Ну и сами интерфейсы (GUI), естественно, будут такими как в новых версиях. Что скажешь?

**Comment by Fox1kFeed** [comment]
Идея хорошая, по результату всё будет видно. У меня ещё смотри какая мысль:

Есть весьма похожий РП на ELR, Faithful называется, он популярный очень, сам знаешь наверное.
Так вот, что если взять Faithful 1.12.2, заменить в нём весь интерфейс на ELR, по возможности некоторые другие текстурки заменить, бахнуть шрифт всей игры на шрифт из ELR и дело в шляпе. Это мне кажется проще будет. Решать уже тебе как исполнителю.

Мне в ELR ОЧЕНЬ понравился шрифт текста всей игры. И интерфейс тоже классный. 3D модели кайфовые, прям респект.

**Comment by lomik31** [comment]
Тут нужно немного подумать ибо есть люди, которые также просили версию на 1.12. Поэтому я не хочу отделять новые версии и эту, так что нужно сохранить какую-то преемственность и соответствие стилю и логике ELR для новых версий.

В свободное время начну делать, но при условии, что по окончании работы она будет также в открытом доступе, а коммерческая сторона вопроса будет, как такое, своеобразное вознаграждение.

**Comment by Fox1kFeed** [comment]
Хорошо, пусть будет в открытом доступе, я согласен. Но у меня одно условие: укажи мой никнейм в подписи к РП. Объясню, когда в minecraft заходишь в меню выбора РП, под названием ресурспака написано "Extra Lomik's resourcepack for minecraft", так вот, я хотел бы, чтоб ты мой никнейм там указал. Оплачиваю то я. Сделаешь?

**Comment by lomik31** [comment]
Что-то вроде "Sponsored by Fox1kFeed" могу организовать

**Comment by Fox1kFeed** [comment]
Да, отлично. Что-ж, значит договорились?
По стоимости примерно сориентируй кстати.

**Comment by lomik31** [comment]
$15-17, по срокам обещать не особо могу

**Comment by Fox1kFeed** [comment]
Ага, ну то-есть 1300₽ - 1500₽
Примерно как и представлял. Хорошо.
Ну всё тогда, жду результат)
Удачи.

**Comment by Fox1kFeed** [comment]
Привет. Есть какие-нибудь новости?

**Comment by lomik31** [comment]
Пока нет. Сейчас веду работу по обновлению с 1.19 до 1.20, а уже после займусь 1.12
Когда новости будут, ты получишь уведомление

**Comment by Fox1kFeed** [comment]
Понял, хорошо.

**Comment by lomik31** [comment]
Собственно, работы осталось уже меньше, чем выполнено. Однако, есть затруднения со шрифтами. До версии 1.13 шрифты в ресурспаке хранились в виде таких вот замечательных (нет) картинок, в которых были текстуры каждого символа:
<details>
<img width="1430" alt="image" src="https://github.com/lomik31/ELR/assets/38201662/a378070b-8e13-41ee-8109-565e95a01b43">
</details>
С версии 1.13 это все дело хранится в универсальном формате шрифтов .ttf
<details>
<img width="329" alt="image" src="https://github.com/lomik31/ELR/assets/38201662/7dffc5f2-7ecf-454e-92a2-1110fb8b7b73">
</details>

И, у меня есть большие сомнения, что я смогу конвертировать этот формат в старые картинки.

**Comment by Fox1kFeed** [comment]
Ну, попытка - не пытка?

**Comment by Fox1kFeed** [comment]
Добрый вечер. Слушай, раз уж работа почти закончена, я считаю пора обговорить детали оплаты твоего труда. Меня маленько пугает то, что ты озвучил цену в долларах. Я думаю не стыдно сказать, что я просто студент и ни единого доллара не имею, у меня всё в рублях. Расскажи пожалуйста как будет происходить оплата.
Перевод на карту тебя устроит, или как?

**Comment by lomik31** [comment]
Ну, "почти закончена" и "сделано более 50%" это все-таки разные вещи)
Фактически, в эту цифру не включено тестирование ресурспака и исправление найденных косяков. Так что еще до финишной прямой еще довольно далеко.
По поводу оплаты скажу, что в долларах указал ибо все-таки универсальная валюта, а из какой ты страны, Я не могу знать. Так что для общего понимания, вот так. Мне в принципе, все равно, какой способ оплаты. Можно и на Российскую карту, и на карту Европы, и перевод криптовалюты..
В общем да, если отправишь просто на карту, это меня вполне устроит.

**Comment by Fox1kFeed** [comment]
Хорошо, я тебя понял.

**Comment by lomik31** [comment]
попытка сделать шрифт №1
![image](https://github.com/lomik31/ELR/assets/38201662/d2ebdf9d-7927-4eb4-a64a-8a5d2454aab8)

**Comment by lomik31** [comment]
У меня следующие новости. Шрифт для английского удалось привести в более-менее адекватное состояние.
![image](https://github.com/lomik31/ELR/assets/38201662/00d89797-43c0-4876-94f6-91118f0f6f1c)

Не замечательно, но и не ужасно. Меня немного триггерит большее расстояние между символами чем в новых версиях, будет ли тебе бросаться в глаза — хз.
Правда, это только для английского языка, цифр и некоторых символов. С русским же возникли трудности. Unicode-кодировку майнкрафт обрабатывает иначе в этой версии, но даже внеся некоторые исправления из-за особенностей русских символов (яркий пример: буква ж), этот шрифт будет несовместим с майном этой версии. Ну, речь именно про unicode-символы. Технически, это сделать-то можно, однако широкие буквы будут сильно обрезаться. Если взять шрифт поменьше размером, то тогда широкие буквы влезут, а узкие будут крохотными по сравнению с английскими. В общем, такие дела.
Что делать, пока не знаю, однако есть пара вариантов.
- Оставить как есть (этот шрифт будет только у англ букв, символов и цифр, а остальное будет с дефолтным майнкрфт шрифтом. 
- Для русских букв использовать другой шрифт (есть парочка классных вариантов), а англ оставить такой, как Я сделал. Вариант не очень предпочтительный, поскольку будет бросаться в глаза различие в шрифтах на разных раскладках (как, в прочем, и в прошлом пункте)
- Рисовать для русских букв шрифт, похожий на тот который на новой версии (лень)
- Использовать другой шрифт вообще для всего
- Не изменять шрифт вовсе (оставить майнкрафтовский)


Вторая же новость заключается в том, что фактически все почти готово. Осталось перевернуть сундуки (лол, да), разобраться со шрифтом, починить пару мелких косяков, еще раз тщательно протестировать и все. Займет не больше недели.

**Comment by Fox1kFeed** [comment]
Прошу прощения, занят был, не мог вовремя ответить.
Итак... Ну, в 1.12.2 русский шрифт в целом чрезвычайно корявый,я пытался этот бред победить сам, но не вышло, привык уже в майн на английском играть. Можешь Русский не трогать, лично мне английского будет достаточно. Но вопрос в другом, если этот ресурспак выйдет в открытый доступ, будут ли другие игроки довольны отсутствием русского шрифта?
Скорее всего нет. 

С нетерпением жду конечного результата)

**Comment by lomik31** [comment]
Ну, получается, закончил. Тут демонстрация (https://dropmefiles.com/HKJ9Q). Если устраивает, напиши мне на почту или в телеграм (@lomik31), я скину координаты для оплаты. После этого запушу сюда коммиты и залью релиз, который уже можно будет скачать и пользоваться.

**Comment by Fox1kFeed** [comment]
![image](https://github.com/lomik31/ELR/assets/152583641/11ab2cdf-ab24-4e7b-aec4-49ef3f1a02dc)

А тут ничего нет...
Прости, я заболел достаточно сильно, температура под 40 фигачит, не мог вовремя ответить. Только вот вчера отпускать потихоньку начало.
Если завтра будет так-же, и опять меня температура не придавит, то завтра и рассчитаюсь с тобой. Искренне извиняюсь что так вот оно вышло.

**Comment by lomik31** [comment]
они неделю там хранятся
новая ссылка: https://dropmefiles.com/icWVG

**Comment by Fox1kFeed** [comment]
Я посмотрел демонстрацию. 
Тут подумал...
А к чёрту эту болезнь, я играть хочу, итак слишком долго ждал.
Сейчас жаропонижающего выпью, и в течении часа-полутора свяжусь с тобой для оплаты.
